trigger:
- none

pr:
- none

jobs:
- job: runCucumber
  displayName: 'Run Cucumber CLI'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    displayName: 'Checkout repository'
    persistCredentials: true

  - task: JavaToolInstaller@0
    displayName: 'Set up JDK 11'
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'

  - script: ./gradlew dependencies
    displayName: 'Install dependencies'

  - script: ./gradlew cucumberCli
    displayName: 'Run Cucumber tests'

  - script: ls -R build/allure/commandline/plugins/behaviors-plugin/
    displayName: 'List report directory contents (debugging)'

  - task: CopyFiles@2
    displayName: 'Upload artifact'
    inputs:
      SourceFolder: 'build/reports/allure-report/allureReport/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/github-pages'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/github-pages'
      ArtifactName: 'github-pages'

- job: deploy
  displayName: 'Deploy to GitHub Pages'
  dependsOn: runCucumber
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo 'Deploy step should be implemented here'
    displayName: 'Deploy to GitHub Pages'